#!/bin/bash

# Modified From: https://gist.github.com/mathiasbynens/674099

if [ "$1" = "-h" -o "$1" = "--help" -o -z "$1" ]; then cat <<EOF
appify v3.0.1 for Mac OS X - http://mths.be/appify
Creates the simplest possible Mac app from a shell script.

Appify takes a shell script as its first argument:

    `basename "$0"` my-script.sh

Note that you cannot rename appified apps. If you want to give your app
a custom name, use the second argument:

    `basename "$0"` my-script.sh "My App"

Copyright (c) Thomas Aylott <http://subtlegradient.com/>
Modified by Mathias Bynens <http://mathiasbynens.be/>
EOF
exit; fi

SCRIPTDIR=$(dirname "$1")

APPNAME=${2:-$(basename "$1" ".sh")}
DIR="$SCRIPTDIR/$APPNAME.app/Contents/MacOS"

if [ -a "$APPNAME.app" ]; then
	echo "$PWD/$APPNAME.app already exists :("
	exit 1
fi

mkdir -p "$DIR"
MYSCRIPT=$(sed 's/#.*$//' "$1" | sed '/^\s*$/d')
read -d '' WHOLEFILE <<GRABTHIS
#!/bin/bash

read -d '' EXECUTE <<DACODE
$MYSCRIPT
DACODE
osascript -e \"tell application \\\"Terminal\\\" to do script \\\"\$EXECUTE\\\"\"


GRABTHIS

echo "$WHOLEFILE" > "$DIR/$APPNAME"
chmod +x "$DIR/$APPNAME"

echo "$SCRIPTDIR/$APPNAME.app"
#open "$DIR"
